### ISSUE TITLE
how to build the ltp based on android 7?

### ISSUE THREAD

**Issue by augustine829** [linux-test-project/ltp#1031]
Hi all,
     I want to run the LTP on imx7d android 7 filesystem, but I can not build it. Do you know what's the version of ltp for android 7 filesystem? how to build it?

**Comment by pevik** [comment]
Please use AOSP fork: https://android.googlesource.com/platform/external/ltp/
(mentioned in our wiki: https://github.com/linux-test-project/ltp/wiki/Supported-kernel,-libc,-toolchain-versions#14-supported-libc)

**Comment by augustine829** [comment]
Hi, I based on kernel 4.9,  and android 7.1
Can it be working now?

**Comment by augustine829** [comment]
can you give me more information about the link of AOSP? I can not find it, thanks so much

**Comment by Avinesh** [comment]
Probably Edward  ( @edliaw ) can help with this.

**Comment by pevik** [comment]
Frankly speaking, Android 7 is so old that even https://lineageos.org/ does not support it. Thus I don't expect AOSP community would do anything about it.
@augustine829 LTP started to be supported in Android 8 (https://android.googlesource.com/platform/external/ltp/+/refs/tags/android-8.1.0_r80) you'll have to port it to Android 7 (AOSP often changed the build system, if you're lucky, just copy this directory will work). Obviously you need to download whole AOSP (120 GB) and build several dependencies in order to build LTP.
Read https://source.android.com/docs/setup/build/building.

I used to try to support LTP on NDK (https://developer.android.com/ndk/guides/other_build_systems), which would allow just to compile it without huge AOSP, but that's much harder.

**Comment by augustine829** [comment]
@pevik Thank you very much for your information. That's to say if I want to run LTP for test Android filesystem. At least I need to use the above of Android 8, right?
