### ISSUE TITLE
getcwd01,readlinkat02 fails in Alpine 3.18 container

### ISSUE THREAD

**Issue by richiejp** [linux-test-project/ltp#1084]
The test passes NULL as the buffer to `getcwd`. This causes musl to allocate a buffer and ignore the length argument. The test then passes unexpectedly.

glibc should do the same, but it possibly checks the length argument or passes it to the syscall.

**Comment by metan-ucw** [comment]
Looks like glibc uses the size argument to allocate the buffer unless it's 0. So I suppose that musl ignores the size completely and allocates the buffer so that it fits the path.

**Comment by richiejp** [comment]
readlinkat02 fails for a similar reason. Except that this time musl checks the buffer size instead and uses a stack buffer.

**Comment by richiejp** [comment]
uclibc-ng does the same as glibc

**Comment by coolgw** [comment]
uclibc-ng: 
https://github.com/wbx-github/uclibc-ng/blob/cdb07d2cd52af39feb425e6d36c02b30916b9f0a/libc/sysdeps/linux/common/getcwd.c#L37

musl:
https://github.com/bminor/musl/blob/79bdacff83a6bd5b70ff5ae5eb8b6de82c2f7c30/src/unistd/getcwd.c#L10

Both malloc buffer if buf==NULL.
https://patchwork.ozlabs.org/project/ltp/patch/20230928010808.15862-1-wegao@suse.com/

**Comment by coolgw** [comment]
uclibc-ng: 
https://github.com/wbx-github/uclibc-ng/blob/cdb07d2cd52af39feb425e6d36c02b30916b9f0a/libc/sysdeps/linux/common/getcwd.c#L37

musl:
https://github.com/bminor/musl/blob/79bdacff83a6bd5b70ff5ae5eb8b6de82c2f7c30/src/unistd/getcwd.c#L10

Both malloc buffer if buf==NULL.
https://patchwork.ozlabs.org/project/ltp/patch/20230928010808.15862-1-wegao@suse.com/

**Comment by pevik** [comment]
> Both malloc buffer if buf==NULL. https://patchwork.ozlabs.org/project/ltp/patch/20230928010808.15862-1-wegao@suse.com/

@coolgw `malloc()` is not relevant to the problem, MUSL fails due the reason described by Richie original report https://github.com/linux-test-project/ltp/issues/1084#issue-1913064764: musl on null buffer allocates a buffer but ignore the length argument. Unlike glibc, uclibc{,-ng}. IMHO also bionic is compatible with glibc, uclibc{,-ng}(https://android.googlesource.com/platform/bionic.git/+/refs/heads/main/libc/bionic/getcwd.cpp), because it uses size on null buffer.
