### ISSUE TITLE
 cross compilation  make error：testcases/commands/ldd/datafiles/Makefile:30: lddfile1.obj.so] Error 1

### ISSUE THREAD

**Issue by xingxinggu** [linux-test-project/ltp#1102]
(.text+0xf4): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
make[4]: *** [/data/user/ltp-20230929/testcases/commands/ldd/datafiles/Makefile:30: lddfile1.obj.so] Error 1
rm lddfile5.o lddfile1.o lddfile2.o lddfile4.o lddfile3.o
make[3]: *** [../../../include/mk/generic_trunk_target.inc:108: all] Error 2
make[2]: *** [../../include/mk/generic_trunk_target.inc:108: all] Error 2
make[1]: *** [../include/mk/generic_trunk_target.inc:108: all] Error 2
make[1]: Leaving directory '/data/user/ltp-20230929/testcases'
make: *** [Makefile:94: testcases-all] Error 2

**Comment by pevik** [comment]
We can hardly help you with cross compilation (we have no idea about your toolchain, you didn't put more info about your environment).

Maybe it's not related to cross compilation, but to some strict flag. I suppose the problem is only with testcases/commands/ldd/datafiles/lddfile1.c, the rest compiles, right? If yes try to run `make V=1` in testcases/commands/ldd/datafiles/.

**Comment by metan-ucw** [comment]
Feel free to reopen if you have a full description as asked by @pevik.
