### ISSUE TITLE
documentation: Unclear what the difference is between TFAIL and TBROK

### ISSUE THREAD

**Issue by roxell** [linux-test-project/ltp#1162]
Reading the documentations for TFAIL and TBROK its not clear that the difference is.

https://linux-test-project.readthedocs.io/en/latest/developers/api_c_tests.html#core-ltp-api

If that can be expanded a bit more, it would be great.

**Comment by pevik** [comment]
Unfortunately we haven't finished transition from Github wiki to readthedocs. Github wiki had more info, which is as backup in https://github.com/linux-test-project/ltp/blob/master/doc/old/, e.g.:

https://github.com/linux-test-project/ltp/blob/fc0b2b471bf232bdd6f46bf43c0e118f3778da3b/doc/old/C-Test-API.asciidoc

`TBROK` Something has failed in test preparation phase.

We should finish converting the docs soon.

**Comment by ngie-eign** [comment]
I don't know what the current stance is, but back when I did more programming in this space TFAIL (to me) was considered an actual invariants failure, whereas TBROK can represent a failure to know the exact result of a test (nondeterminism) due to preconditions failing, e.g., failure to create a directory, load a module, etc. In more modern/traditional test frameworks, TBROK might be expressed with TSKIP and variously scoped fixtures, e.g., package, module, suite, or test, if you are familiar with GoogleTest or pytest.

**Comment by metan-ucw** [comment]
I've send a patch that hopefully clarifies it:

http://patchwork.ozlabs.org/project/ltp/list/?series=425706
