### ISSUE TITLE
IPsec offloading support

### ISSUE THREAD

**Issue by mahi657** [linux-test-project/ltp#1195]
I wanted to know, if there are any test cases available already for testing IPsec offloading feature? If not, is anyone working on it from the community ?

**Comment by metan-ucw** [comment]
There seems to be some basic ipsec stress tests in LTP but I have no idea what exactly they do or even if they work.

As far as I know nobody works on making better ipsec tests, we as the LTP community struggle with covering the basics, e.g. syscalls and it's very unlikely that we will ever get to write complex tests for network related functionality.

**Comment by chetjain** [comment]
The existing IPSEC tests seems to be old and applicable for only secure transmission support. Crypto offload is not covered in the existing test bucket. Since crypto offload is getting more popular and it has performance benefits, more adoptions are on the way.
https://docs.nvidia.com/networking/display/ofedv502180/ipsec+crypto+offload
Worth enabling the existing coverage with offload support.
