### ISSUE TITLE
getcwd01 and getcwd02 failed after new cleanup.

### ISSUE THREAD

**Issue by Vertigo0709** [linux-test-project/ltp#133]
These 2 cases have just failed on my system as below

>     root@mx6q:/opt/ltp/testcases/bin# ./getcwd01
>     tst_test.c:794: INFO: Timeout per run is 0h 05m 00s
>     getcwd01.c:69: FAIL: getcwd() failed unexpectedly, expected EFAULT: ERANGE
>     getcwd01.c:73: PASS: getcwd() failed as expected: ENOMEM
>     getcwd01.c:73: PASS: getcwd() failed as expected: EINVAL
>     getcwd01.c:73: PASS: getcwd() failed as expected: ERANGE
>     getcwd01.c:73: PASS: getcwd() failed as expected: ERANGE
> 
>     root@mx6q:/opt/ltp/testcases/bin# ./getcwd02
>     tst_test.c:794: INFO: Timeout per run is 0h 05m 00s
>     getcwd02.c:53: FAIL: getcwd() failed: ERANGE
>     getcwd02.c:59: FAIL: getcwd() returned unexpected directory: /var/volatile/tmp, expected: /tmp
>     getcwd02.c:53: FAIL: getcwd() failed: ERANGE

Quick look into the code, there's some points that made the cases failed
- New version run in /tmp. This folder is easily linked to another place (eg. in may case, it's /var/volatile/tmp), therefore the size = 10 will be not enough for the path length, then the ERANGE appears sooner than EFAULT. Should PATH_MAX be used?
- getcwd02 also compare the path with expected directory /tmp (hardcoded in getcwd02). Similar as above, it'll be failed because the real directory return is /var/volatile/tmp. I wonder if we should compare like this way ? 

@metan-ucw : I cannot find Xiao Yang who is the author of these new commits on github. Could you help to contact the author to update it if need or give some ideas ?

PS: edited. Update a little bit for later reference from others, not buffer[5] is issue, issue should be size = 10 of getcwd

**Comment by metan-ucw** [comment]
The fix for the getcwd01 should be as easy as increasing the buffer size, I will commit that right away.

For the getcwd02, we should probably use readlink() in the test setup to get the link content. I will have a look into that.

@Vertigo0709 : Only a few LTP devs are on GitHub, but you can reach all of them on the mailing list.

**Comment by Vertigo0709** [comment]
@metan-ucw 
Yes, I'm just afraid there's many mails recently and people will miss it (I also have some patches and issue, but maybe we have many patches to check now), so I post it here :-)

Thanks a lot, I'm looking forward to your fixs on both testcases.

**Comment by metan-ucw** [comment]
The mailing list is still preferred way of communication and emails are usually answered, albeit it sometimes takes time (too much work for the small LTP team...).

Anyway the first test has been fixed, the second one will be a bit more complicated since the path from readlink has to be canonicalized before we compare it with the one from getcwd. If I just put readlink to setup it fails in most of the cases either because the symlink is a relative or because there is missing / at the end of the path, etc.

**Comment by Vertigo0709** [comment]
Thanks for your commit. Yes, the 2nd case is a little bit more complicated. I see the old version use popen with pwd, before compare with getcwd. Not test yet but seems it also cannot pass if the symlink is a relative. realpath() can help in this case ?

PS: I'll use mailing list next time. I'm not so hurry, so I can wait, your team just can take your time :-)
