### ISSUE TITLE
TWARN: tst_rhost_run: command not defined

### ISSUE THREAD

**Issue by hardiksingh-rathore** [linux-test-project/ltp#214]
I'm running ltp-20170516 (latest release) in buildroot but getting a warning as given below
`TWARN: tst_rhost_run: command not defined`

May be I'm missing some package.
Could someone please help me to solve this issue?

And it should be from _testcases/bin/test_net.sh_

`# ./network.sh -b

network_settings 1 TINFO: initialize 'lhost' 'ltp_ns_veth2' interface
ADDRCONF(NETDEV_UP): ltp_ns_veth2: link is not ready
network_settings 1 TINFO: set local addr 169.254.225.188/24
network_settings 1 TINFO: set local addr fd00:1:1:1::2/64
network_settings 1 TINFO: initialize 'rhost' 'ltp_ns_veth1' interface
network_settings 1 **TWARN: tst_rhost_run: command not defined**
netlink: 20 bytes leftover after parsing attributes.
`

**Comment by pevik** [comment]
That's strange, as `test_net.sh` is loaded in `network.sh`.

Do you run `network.sh` from installed directory? Buildroot installs into `/usr/lib/ltp-testsuite` ([1]), so running it like this should work:

`/usr/lib/ltp-testsuite/testscripts/network.sh -b`

If not, could you please post shell which you're using or more info about your OS (sharing your buildroot config might help)?

[1] https://git.busybox.net/buildroot/tree/package/ltp-testsuite/ltp-testsuite.mk#n34

**Comment by hardiksingh-rathore** [comment]
Hi Pevik,

Buildroot configuration -
[olimex_rk3188_buildroot_defconfig.txt](https://github.com/linux-test-project/ltp/files/1337883/olimex_rk3188_buildroot_defconfig.txt)

And Kernel (3.0.36) Configuration
[kernel_config.txt](https://github.com/linux-test-project/ltp/files/1337901/kernel_config.txt)

ltp-testsuite config
[ltp-testsuite.txt](https://github.com/linux-test-project/ltp/files/1337908/ltp-testsuite.txt)

Logs from target machine
`# pwd
/usr
# ls
IDcheck.sh       lib32            sbin             testscripts
Version          runltp           scenario_groups  ver_linux
bin              runltplite.sh    share
lib              runtest          testcases
# cd testscripts/
# ls
adp.sh                             ltpdmmapper.sh
adp_children.sh                    ltpfslvm.sh
adp_test.sh                        ltpfsnolvm.sh
autofs1.sh                         ltpstress.sh
autofs4.sh                         network.sh
diskio.sh                          runEALtests.sh
exportfs.sh                        sysfs.sh
load_stress_all_kernel_modules.sh  test_fs_bind.sh
ltp-aiodio.sh                      test_realtime.sh
ltp-scsi_debug.sh                  tpm_tools.sh
# ./network.sh -b
network_settings 1 TINFO: initialize 'lhost' 'ltp_ns_veth2' interface
ADDRCONF(NETDEV_UP): ltp_ns_veth2: link is not ready
network_settings 1 TINFO: set local addr 169.254.225.188/24
network_settings 1 TINFO: set local addr fd00:1:1:1::2/64
network_settings 1 TINFO: initialize 'rhost' 'ltp_ns_veth1' interface
network_settings 1 TWARN: tst_rhost_run: command not defined
netlink: 20 bytes leftover after parsing attributes.
netlink: 20 bytes leftover after parsing attributes.
netlink: 20 bytes leftover after parsing attributes.
netlink: 20 bytes leftover after parsing attributes.
netlink: 20 bytes leftover after parsing attributes.
network_settings 1 TWARN: tst_rhost_run: command not defined
netlink: 20 bytes leftover after parsing attributes.
netlink: 20 bytes leftover after parsing attributes.
nettiwo: _0etyieg l1 tover aftea35mng ARNriem.
nstlirkos20rbunesclemtov rnoftdefinesing attributes.
netlink: 20 bytes leftover after parsing attributes.
netlink: 20 bytes leftover after parsing attributes.
netlink: 20 bytes leftover after parsing attributes.
netlink: 20 bytes leftover after parsing attributes.
netlink: 20 bytes leftover after parsing attributes.
netlink: 20 bytes leftover after parsing attributes.
network_settings 1 TWARN: tst_rhost_run: command not defined
`

**Comment by pevik** [comment]
Hi hardiksingh-rathore,

You're using LTP old config from this revision
https://git.busybox.net/buildroot/commit/?id=3608bf022a1c70048243a5aebd4fc2fd9b80a3c2
with changed ltp release.
Note LTP might have some problems if non-default prefix is used, which buildroot does, but that's not a root of this problem.
Not sure if why you're using this particular config fire, which was not released by any stable release.
Could you please try it with last stable buildroot release and with fresh install (remove at least `output/build/` from buildroot tree)?

**Comment by hardiksingh-rathore** [comment]
Hi Pevik,
Now I'm using the ltp-testsuite-20160126 which is pre-installed in buildroot. 
So getting same error but logs are different I mean it's trying to establish ssh connection with remote machine. logs are as given below.
[logs.txt](https://github.com/linux-test-project/ltp/files/1340655/logs.txt)

Thanks,
Hardik

**Comment by pevik** [comment]
Hi Hardik,

logs shows that tests are more or less working.

_# icmp6-multi-diffip01    1  TFAIL  :  ltpapicmd.c:193: Test broken: locale: command not found_
Your system is missing some binaries, but the previous error is ok, so I'd propose to close this bug.

networkstress.sh was removed more than one year ago
https://github.com/linux-test-project/ltp/commit/fddb4f3c72cf0be197fdecbdf97a6f583e3e03bc
e.g. in 20160920 (previous stable release).
You really need to 1) use last stable buildroot 2) make a clean build in buildroot. If you don't use last stable build we both wasting our time trying to solve old bugs which was already fixed in newer releases.
Some network test has been fixed in newer releases, that's another benefit.

_And to make it work I had to copy test_net.sh and test.sh in "testscript" dir from "testcases/bin/" dir._
You're not supposed to do it. That's a sign that the installation is wrong. That can be caused by your mistake or buildroot error (the problem isn't in LTP code). Again: please, use last LTP, either via buildroot or compiled standalone (you can cross-compile LTP and install it locally and than copy it to your target, although it's probably easier for you to build it via buildroot).

Variables in network.txt: it's better to set environment variables and not touch test_net.sh (docs are wrong, see proposed update on LTP mailing list: http://lists.linux.it/pipermail/ltp/2017-September/005719.html).

You can use netns instead of ssh based testing, read doc in 
https://github.com/linux-test-project/ltp/blob/master/testcases/network/README.md
https://github.com/linux-test-project/ltp/blob/master/INSTALL (5. The network tests are executed by running the network.sh script.)

**Comment by hardiksingh-rathore** [comment]
Hi Pevik,
You are right.
I should use latest and official buildroot. It'll solve many bugs and also having latest packages like ltp-20170516.
So closing this issue here.

Thanks,
Hardik
