### ISSUE TITLE
du01.sh failed

### ISSUE THREAD

**Issue by wrjiafang** [linux-test-project/ltp#263]
Hi my failed test log is: 
3 TFAIL: 'du -a' failed
 3 TINFO: Looking for '^\(0\|4\)[[:space:]]\.\/testdir\/testsymlink' in:
10241   ./testfile
1       ./testdir/testsymlink
3       ./testdir
2       ./basedir
10248   .
 4 TFAIL: 'du --all' failed
 4 TINFO: Looking for '^\(0\|4\)[[:space:]]\.\/testdir\/testsymlink' in:
10241   ./testfile
1       ./testdir/testsymlink
3       ./testdir
2       ./basedir

I found the problem is "TST_TMPDIR=$(mktemp -d "$TMPDIR/LTP_$TST_ID.XXXXXXXXXX")"
If I "mkdir -p /tmp/basedir" and then use "TST_TMPDIR="/tmp/basedir", everything is fine.
Meanwhile if I create soft symlink under /home or other files, everything is fine.

I don't know why the symlink size is 1 when using "mktemp" directory.

Does anyone know about this ?

Thanks a lot!

**Comment by wrjiafang** [comment]
I just found that my $TMPDIR is a ext4 file system.
/dev/loop0 on /ltp/tmpdir type ext4 (rw,relatime,mand,seclabel,data=ordered)

But don't know why ext4 file system will impact the du command

**Comment by metan-ucw** [comment]
Normally symlinks have zero size in ext4, which is I suppose because these are stored directory in the data allocated for a directory listing if it's shorter than 60 bytes.

Looking at the mount options it may be the case that the seclabel option causes data block to be allocated for the symlink in order to store extended attributes, but that is just a guess. Can you try to remount the filesystem without the seclabel option and rerun the test?

**Comment by metan-ucw** [comment]
Closing since there was no response for last few years, feel free to reopen if you can still reproduce the failure.
