### ISSUE TITLE
fsstress -l 0 does not loop forever

### ISSUE THREAD

**Issue by megari** [linux-test-project/ltp#32]
When I run the latest fsstress (as of commit 0841eee) with the -l 0 option, the program exits almost immediately:

> time ./fsstress -X -w -d /tmp/fsstress-dir -l 0 -n 100 -p 100 -s urandom
> seed = 1427394847
>
> real	0m1.770s
> user	0m0.073s
> sys	0m0.732s

Is this as intended?

**Comment by metan-ucw** [comment]
Looks like the parent process sends SIGTERM to the whole process group to reap the child processes at the end of the loop but it also gets the signal and sets it should_exit flag in signal handler.

And looking at the xfstest fsstress.c (from which the change was backported) it does not support -l option at all. So this looks like bug caused by the wrongly backported patch.

**Comment by megari** [comment]
Yes, I came to the same conclusion. A quick hack around this would be to ignore SIGTERM for the duration of the kill() invocation, but this is of course racy.

**Comment by metan-ucw** [comment]
Looking at the code closely I think that the whole snippet:

```
...
    action.sa_flags = SA_RESTART;
    sigaction(SIGTERM, &action, 0);
    kill(-getpid(), SIGTERM);
...
```

Should be inside:

```
    if (should_stop) {

    }
```

Because otherwise the parent would be the only process in it's process group and sending the kill does not make much sense.


And that change seems to fix the -l parameter for me as well.
