### ISSUE TITLE
Have a look at testcases/kernel/syscalls/epoll2/ tests

### ISSUE THREAD

**Issue by metan-ucw** [linux-test-project/ltp#381]
These are not compiled by default, possibly broken needs some investigation. Maybe we already cover everything we need in syscalls/epoll_* testcases and we can just delete the whole directory.

**Comment by xuyang0410** [comment]
@metan-ucw,  this is a epoll* case with [PCL](http://www.xmailserver.org/libpcl.html). I am working on this.

**Comment by xuyang0410** [comment]
@metan-ucw  I guess we can't delete the whole directory because the case is different from other syscalls/epoll*. It used Portable Coroutine Library (we must install pcllib rpm before run, it provides pcl.h and libpcl.so) and epoll*  to test  three situations (blaster httpd pipetest).  I prefer to remove sub directory and only remove Makefile,epoll-test.c,dbllist.h( other files is useless IMO)

**Comment by metan-ucw** [comment]
I would say that depending on PCL is no-go from the start, that library does not seem to be included in distributions in the first place. So we should either rewrite these tests without it, or simply remove them if rewrite would be too much work.

**Comment by xuyang0410** [comment]
feel free to close this issue. It has been removed since [syscalls/epoll2: Remove PCL epoll test ](https://github.com/linux-test-project/ltp/commit/7d683232465d6886d9072e635eb39195629855b9)
