### ISSUE TITLE
growfiles test tend to fail with "no enough disk space" on system with ~2G free space

### ISSUE THREAD

**Issue by Cypresslin** [linux-test-project/ltp#389]
**Summary:**
Test HW:
* KVM node (8G disk space) deployed with Ubuntu 18.04

It looks like test gf18 in growfiles test will fail first with 2.3G free space on the system.
If the disk space drops to 1.7G, gf15 and gf18 will fail.
If the disk space drops to 1.5G, gf14, gf15 and gf18 will fail.
(gf01 will fail with around 1.5G free space, but I'm not sure what is the correct threshold)

**Detailed report:**

A: 18.04
Disk space:
/dev/vda1 7.3G 4.7G 2.3G 68% /

B: 18.04 + proposed packages
Disk space:
/dev/vda1 7.3G 5.2G 1.7G 76% /

C: 18.04 + linux-kvm kernel
Disk space:
/dev/vda1 7.3G 4.9G 2.1G 71% /

D: 18.04 + linux-kvm kernel + proposed packages:
Disk space:
/dev/vda1 7.3G 5.5G 1.5G 79% /

For node A, C (2.3, 2.1G free space), only the gf18 test will fail:
<<<test_start>>>
tag=gf18 stime=1535959767
cmdline="growfiles -W gf18 -b -e 1 -i 0 -L 120 -w -u -r 10-5000 -I r -l -S 2 -f Lgf04_ -d $TMPDIR"
contacts=""
analysis=exit
<<<test_output>>>
growfiles(gf18): 1218 growfiles.c/2037: 523098 tlibio.c/735 write(6, buf, 1) ret:-1, errno=28 No space left on device
gf18 1 TFAIL : growfiles.c:132: Test failed
<<<execution_status>>>
initiation_status="ok"
duration=62 termination_type=exited termination_id=1 corefile=no
cutime=1247 cstime=2400
<<<test_end>>>

For node B (1.7G free space), gf15 and gf18 will fail
The failure in gf15 is not "No space left on device":
<<<test_start>>>
tag=gf15 stime=1535960672
cmdline="growfiles -W gf15 -b -e 1 -u -r 1-49600 -I r -u -i 0 -L 120 -f Lgfile1 -d $TMPDIR"
contacts=""
analysis=exit
<<<test_output>>>
growfiles(gf15): 1140 growfiles.c/2249: 78642 tlibio.c/1002 pwrite(6, buf, 46818, 1951330224) returned=80
growfiles(gf15): 1140 growfiles.c/1752: 78642 Hit max errors value of 1
gf15 1 TFAIL : growfiles.c:132: Test failed
<<<execution_status>>>
initiation_status="ok"
duration=17 termination_type=exited termination_id=1 corefile=no
cutime=1306 cstime=302
<<<test_end>>>

For node D (1.5G free space), gf14, gf15 and gf18 will fail

https://bugs.launchpad.net/ubuntu-kernel-tests/+bug/1790445

**Comment by metan-ucw** [comment]
Looking at the tests the parameters define runtime and interval for write buffer size. The actual write size is random on each write and chosen from the pre-defined interval. The problem is that the resulting file size depends on the I/O speed of the underlying device and partly on the interval size. I cannot see how we can easily approximate the minimal size for the test based on the test parameters alone.

BTW: The VMs I use for testing do have 20GB disks  and everything works fine even on a system with fast solid state storage, so maybe the best we can do is to write down the recommendation to use at least 20GB disk for FS tests.

**Comment by pevik** [comment]
@Cypresslin Here is a fix for your problem, if you wish to test it:
https://patchwork.ozlabs.org/patch/985313/

**Comment by Cypresslin** [comment]
Sorry forgot to came back on this,
yes the patched version works fine, thank you!
