### ISSUE TITLE
travis: test on different distros with docker

### ISSUE THREAD

**Issue by pevik** [linux-test-project/ltp#448]
Currently we do travis tests with ubuntu-toolchain-r-test, which allows us to get different gcc and clang versions. But we test on single glibc and kernel headers version.
Testing on different distros with docker (or chroot, but docker is probably better) would give us less variety of compiler versions, but brought different glibc and kernel headers, which is more important. And we could even test for different libc.
This also (hopefully) as side effect fixes problems with timeouts when installing toolchains from ubuntu-toolchain-r repository (travis-ci/travis-ci#9112).

Some inspiration from snapper:
https://github.com/openSUSE/snapper/blob/master/.travis.yml

**Comment by richiejp** [comment]
> Testing on different distros with docker (or chroot, but docker is probably better) would give us less variety of compiler versions, but brought different glibc and kernel headers, which is more important.

We can test all the versions (assuming Travis allow us to extend the test matrix that far), we just need to build/find the right docker images.

I would prefer to use VMs instead of containers for the CI, so that we could run the test suite itself without worrying about breaking the host environment, but I'm not sure what choice we have for that other than a heavy weight solution like OpenQA or maybe Vargrant or Terraform. My feeling is Docker will be much simpler to setup and use than these, but I would be happy to be proven wrong.

**Comment by pevik** [comment]
I'd like to have these separate: travis with docker for quick compilation checks and then other CI which would actually run the tests.

**Comment by pevik** [comment]
Patchset implementing it
http://lists.linux.it/pipermail/ltp/2018-December/010341.html
https://patchwork.ozlabs.org/project/ltp/list/?series=82852&state=*

**Comment by pevik** [comment]
Merged v2 as 24519c14a.
