### ISSUE TITLE
LTP tries to build open-posix tests with default cc even if custom compiler is provided

### ISSUE THREAD

**Issue by mnowaksuse** [linux-test-project/ltp#54]
On master I configure LTP to be build with GCC5:
```
CC=/usr/bin/gcc-5 ./configure --with-open-posix-testsuite
make -j$(getconf _NPROCESSORS_ONLN) all
```
All but open-posix tests are built with GCC5. The open-posix test are attempted to be build with stock GCC (/usr/bin/gcc I guess) which is not present in my installation (SLES 12SP1 with GCC5 from Toolchain Module):

```
make[5]: Leaving directory '/root/ToolchainModuleTesting/BUILD/ltp-master/testcases/kernel/include'
/usr/bin/gcc-5 -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall -W -Wold-style-definition -D_FORTIFY_SOURCE=2 -I/root/ToolchainModuleTesting/BUILD/ltp-master/testcases/kernel/include -I../../../../include -I../../../../include   -L../../../../lib  delete_module01.c   -lltp -o delete_module01
...
make[4]: Leaving directory '/root/ToolchainModuleTesting/BUILD/ltp-master/testcases/kernel/module/delete_module'
...
Generating buildonly Makefiles
Generating runnable Makefiles
conformance/interfaces/pthread_create/15-1.c should be test.
Generating test-tools Makefiles
make[3]: Leaving directory '/root/ToolchainModuleTesting/BUILD/ltp-master/testcases/open_posix_testsuite'
make[3]: Entering directory '/root/ToolchainModuleTesting/BUILD/ltp-master/testcases/open_posix_testsuite/conformance'
make[4]: Entering directory '/root/ToolchainModuleTesting/BUILD/ltp-master/testcases/open_posix_testsuite/conformance/behavior'
make[5]: Entering directory '/root/ToolchainModuleTesting/BUILD/ltp-master/testcases/open_posix_testsuite/conformance/behavior/timers'
/bin/sh: cc: command not found
conformance/behavior/timers/1-1 compile FAILED; SKIPPING
/bin/sh: cc: command not found
conformance/behavior/timers/2-1 compile FAILED; SKIPPING
make[5]: Leaving directory '/root/ToolchainModuleTesting/BUILD/ltp-master/testcases/open_posix_testsuite/conformance/behavior/timers'
...
```

**Comment by metan-ucw** [comment]
The Open Posix Testsuite build system was never integrated with the rest of the LTP. It has separate build system etc. which is mainly because it's intended to be usable on any POSIX-like platform. Looking into the LTP build system all the ```--with-open-posix-testsuite``` configure option does is including the ```open_posix_testsuite``` directory in the recursive build. Now the ```CC```, ```CFLAGS```, and ```LDFLAGS``` are set in the ```include/mk/config.mk``` file which is not used by the Open Posix Testsuite build system at all since it's intended to be used separately.

I will try to figure out a way how to propagate the parameters to the Open Posix Testsuite while avoiding unexpected behaviour but I'm not sure that it's doable (since we have to stick with POSIX make there).

You can easily workaround this for now by exporting ```CC=/usr/bin/gcc-5``` before you do the build which should be picked up by both ```configure``` and ```make```.
