### ISSUE TITLE
net.tirpc_tests: is this sunset?

### ISSUE THREAD

**Issue by chetjain** [linux-test-project/ltp#589]
(1) Is net.tirpc_tests supported on IBM Power systems?
(2) Or these testsuites are sunset?

None of the testcases under "./testcases/network/rpc/rpc-tirpc/tests_pack" are copied to /opt/ltp/testcases/bin during installation of LTP.

Attempt to run ./runltp -f net.tirpc_tests
fails with the below error 
execvp of 'rpc_test.sh' (tag tirpc_rpcb_getaddr) failed.  errno:2  No such file or directory"

Tried, copying rpc_test.sh under /opt/ltp/testcases/bin, but it further fails looking for  tirpc_* programs,
But  tirpc_* are not compiled at all!
/opt/ltp/testcases/network/rpc/rpc-tirpc/tests_pack

Please suggest. 
Thanks
CJ

**Comment by chetjain** [comment]
Same problem, when attempted to run 
./runltp -f net.rpc 
****************************************************************************************************
initiation_status="pan(305107): execvp of 'rpc01' (tag rpc01) failed.  errno:2  No such file or directory"
<<<execution_status>>>
initiation_status="pan(304430): execvp of 'rpc01' (tag rpc01) failed.  errno:2  No such file or directory"
duration=2 termination_type=exited termination_id=2 corefile=no
cutime=0 cstime=0
<<<test_end>>>
<<<test_start>>>
tag=rpcinfo stime=1571395016
cmdline="rpcinfo01"
contacts=""
analysis=exit
<<<test_output>>>
<<<execution_status>>>
initiation_status="pan(304430): execvp of 'rpcinfo01' (tag rpcinfo) failed.  errno:2  No such file or directory"
duration=0 termination_type=exited termination_id=2 corefile=no
cutime=0 cstime=0
<<<test_end>>>
<<<test_start>>>
tag=rup stime=1571395016
cmdline="rup01"
contacts=""
analysis=exit
<<<test_output>>>
<<<execution_status>>>
initiation_status="pan(304430): execvp of 'rup01' (tag rup) failed.  errno:2  No such file or directory"
duration=0 termination_type=exited termination_id=2 corefile=no
cutime=0 cstime=0
<<<test_end>>>
<<<test_start>>>
tag=rusers stime=1571395016
cmdline="rusers01"
contacts=""
analysis=exit
<<<test_output>>>
<<<execution_status>>>
initiation_status="pan(304430): execvp of 'rusers01' (tag rusers) failed.  errno:2  No such file or directory"
duration=0 termination_type=exited termination_id=2 corefile=no
cutime=0 cstime=0
<<<test_end>>>
incrementing stop
INFO: ltp-pan reported all tests PASS
LTP Version: 20190517
****************************************************************************************************

**Comment by chetjain** [comment]
Even for ./runltp -f net.rpc_tests

Overall, need to understand, how to run these rpc tests?
[rpc_error.txt](https://github.com/linux-test-project/ltp/files/3720872/rpc_error.txt)

**Comment by chetjain** [comment]
Hi,
Any update?

**Comment by pevik** [comment]
@chetjain `execvp of 'rpc_test.sh' (tag rpc_svcerr_weakauth) failed.  errno:2  No such file or directory"` mean that `$PATH` is not set correctly.

The easiest way is to run them as network tests
```
/opt/ltp/testscripts/network.sh -c # net.rpc_tests
/opt/ltp/testscripts/network.sh -d # net.tirpc_tests
```
For more info see
https://github.com/linux-test-project/ltp/tree/master/testcases/network
https://github.com/linux-test-project/ltp/wiki/User-Guidelines

**Comment by pevik** [comment]
> (1) Is net.tirpc_tests supported on IBM Power systems?

It can certainly be run on powerpc.

> (2) Or these testsuites are sunset?

What is sunset?

**Comment by chetjain** [comment]
> 
> 
> > (2) Or these testsuites are sunset?
> 
> What is sunset?
--basically was asking, if these tests were retired?. You clarified, that it can be run on ppc.
May be as a next step, please look into the next set of failure and assist us, what are we missing?

**Comment by chetjain** [comment]
> 
> 
> @chetjain `execvp of 'rpc_test.sh' (tag rpc_svcerr_weakauth) failed. errno:2 No such file or directory"` mean that `$PATH` is not set correctly.
> 
> The easiest way is to run them as network tests
> 
> ```
> /opt/ltp/testscripts/network.sh -c # net.rpc_tests
> /opt/ltp/testscripts/network.sh -d # net.tirpc_tests
> ```
> 
> For more info see
> https://github.com/linux-test-project/ltp/tree/master/testcases/network
> https://github.com/linux-test-project/ltp/wiki/User-Guidelines

Yeah, I verified with both methods, its same result.  PATH is absolutely fine, because, all other tests suites are working fine, except rpc ones.

**Comment by pevik** [comment]
I guess there is something wrong with your installation. `initiation_status="pan(304430): execvp of 'rpcinfo01' (tag rpcinfo) failed. errno:2 No such file or directory"` is quite obvious that `rpcinfo01` file cannot be find (or the `PATH` is wrong, but you claimed to be correct). Do you have `/opt/ltp/testcases/bin/rpcinfo01` (or `$LTPROOT/testcases/bin/rpcinfo01` if LTP installed elsewhere that the default `/opt/ltp`)?
Did you install LTP correctly? This looks as a typical wrong installation problem.
https://github.com/linux-test-project/ltp#compiling-and-installing-all-testcases

Ad test retirement. These tests certainly needs cleanup (some of them might be failing), but that's another issue.

**Comment by sameerasimha-ltp** [comment]
LTP was installed as per above link  , but rup01 ,rpcinfo01 was not found in repective bin directory .[used Compiling and installing all testcases ]

I have installed  libtirpc and rpc releated rpm's too files on my machine  
Atlast  i have tried to compile one by one ,  getting the following  error
Note : since rsh/telnet deprecated not installed those rpm's .
##############################################
[root@MSS-LPAR tests_pack]# ls
lib       Makefile.inc   rpc_suite  rpc_svc_2        tirpc_svc_1   tirpc_svc_2  tirpc_svc_4  tirpc_svc_6  tirpc_svc_8
Makefile  rpc_cleaner.c  rpc_svc_1  tirpc_cleaner.c  tirpc_svc_11  tirpc_svc_3  tirpc_svc_5  tirpc_svc_7  tirpc_svc_9


[root@MSS-LPAR tests_pack]# make
make -C /MY_LTP/ltp-master/testcases/network/rpc/rpc-tirpc/tests_pack/lib -f "/MY_LTP/ltp-master/testcases/network/rpc/rpc-tirpc/tests_pack/lib/Makefile" all
make[1]: Entering directory '/MY_LTP/ltp-master/testcases/network/rpc/rpc-tirpc/tests_pack/lib'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/MY_LTP/ltp-master/testcases/network/rpc/rpc-tirpc/tests_pack/lib'
gcc -g -O2 -g -O2 -fno-strict-aliasing -pipe -Wall -W -Wold-style-definition -D_FORTIFY_SOURCE=2  -I/MY_LTP/ltp-master/testcases/network/rpc/rpc-tirpc/tests_pack/lib -pthread -I../../../../../include -I../../../../../include -I../../../../../include/old/   -L/MY_LTP/ltp-master/testcases/network/rpc/rpc-tirpc/tests_pack/lib -L../../../../../lib  tirpc_cleaner.c    -lrpc-tirpc -o tirpc_cleaner
In file included from tirpc_cleaner.c:31:
../../../../../include/lapi/rpc.h:36:3: error: #error Missing rpc headers!
 # error Missing rpc headers!
   ^~~~~
tirpc_cleaner.c: In function ‘main’:
tirpc_cleaner.c:39:16: warning: implicit declaration of function ‘atoi’ [-Wimplicit-function-declaration]
  int progNum = atoi((char *)argc[1]);
                ^~~~
tirpc_cleaner.c:41:2: warning: implicit declaration of function ‘svc_unreg’ [-Wimplicit-function-declaration]
  svc_unreg(progNum, VERSNUM);
  ^~~~~~~~~
tirpc_cleaner.c:36:14: warning: unused parameter ‘argn’ [-Wunused-parameter]
 int main(int argn, char *argc[])
          ~~~~^~~~
make: *** [<builtin>: tirpc_cleaner] Error 1

**Comment by metan-ucw** [comment]
This looks like you haven't run the configure script after you have installed rpc devel libraries.

**Comment by pevik** [comment]
Yes I really think it's a configuration issue during installation, not a bug in LTP.

**Comment by manjuhr1** [comment]
1. Need to install "libtirpc-devel" package.
2. Run configure :  make autotools ; ./configure
3. make
4. make install

This helps to get the RPC related testcases compiled on PowerPC Linux..  

libtirpc-devel package does not get installed by default on ppc64/ppc64le Linux. Is it required to document (in README or some other place) that 'libtirpc-devel' needs to be installed in order to execute RPC related testcases ?

Please suggest.. 

Thanks,
Manju

**Comment by pevik** [comment]
LTP has many dependencies, look at [travis folder](https://github.com/linux-test-project/ltp/tree/master/travis) for dependencies for your distro. libtirpc-devel (or libtirpc-dev) is not a requirement. But recently (c7d2a7458) was added `pkg-config` as build dependency, which is also visible in travis scripts (and described in the commit message).
