### ISSUE TITLE
rpc_pmap_rmtcall FAIL

### ISSUE THREAD

**Issue by wangchuanguo** [linux-test-project/ltp#725]
"rpc_pmap_rmtcall rpc_test.sh -s rpc_svc_1 -c rpc_pmap_rmtcall" in file controllers   FAILED
1、done: systemctl stop firewalld && setenforce 0
2、rpcinfo could see 536875000 (tcp and udp)
3、the pmap_getport() successed in rpc_pmap_rmtcall.c and failed at pmap_rmtcall()

Help, please!

**Comment by pevik** [comment]
RPC tests might be broken on netns if you test them on glibc.

Ad *Help, please!* without giving more details (distro, kernel and libc version, last time it not failed) is just a very useless report.

**Comment by wangchuanguo** [comment]
Thanks, 
OS: Centos8.2-2004,   and glibc-2.28, 
This is my first rpc test, And I'll try it between 2 device, not netns!

**Comment by pevik** [comment]
You should use libtirpc (which is TI-RPC implementation), because glibc implementation (SUN RPC) was unmaintained and buggy (finally removed in glibc 2.32, see https://sourceware.org/git/?p=glibc.git;a=commit;h=5500cdba4018ddbda7909bc7f4f9718610b43cf0)

But even with libtirpc some tests fail. Tests are broken, unreliable, rewritten from scratch in tirpc upstream and removed from here, see https://github.com/linux-test-project/ltp/issues/621 and some [other related issues](https://github.com/linux-test-project/ltp/labels/TI-RPC%20%2F%20Sun%20RPC) (incomplete list).
=> don't worry that much about these failures.
