### ISSUE TITLE
Testing cve-2017-2671 on single core machine takes a considerable amount of time

### ISSUE THREAD

**Issue by ycliang-tw** [linux-test-project/ltp#766]
Hi,
As the title read, 
what I observed is cve-2017-2671 along with other testcases that use fuzzy sync library
would take very long to execute on single core machines, while they finish in a short amount of time on multi-core machines.

I've studied the fuzzy sync library for a little bit. Is it safe to say that the reason for this phenomenon is 
because the fzsync library uses polling mechanism to check if a specific condition is met.
On single core machine, there will always be only one thread running at a time, so polling would consume a lot of time.
(the condition would not change because there is no other thread executing)
Whereas, on Multi-core machine, there could be multiple thread running at the same time, so polling might succeed in relatively short time.

Or is there some other consideration should be taken into account ?

Thanks in advance,
Leo

**Comment by ycliang-tw** [comment]
I've also use perf to gather some logs as follow
+ This is perf data of cve-2017-2671 on single core machine: (about 4.5 hrs to finish this test)
![cve-perf-log-all](https://user-images.githubusercontent.com/32037392/104418454-e2f1c580-55b1-11eb-956c-c93707cdf708.PNG)
+This is cve-2017-2671 on multi-core machine: (about 2 mins to finish the test)
![cve-perf-log-all-a25mp](https://user-images.githubusercontent.com/32037392/104418676-44b22f80-55b2-11eb-9cff-d0eff357e391.PNG)

**Comment by richiejp** [comment]
Thanks for reporting this.

I guess that on single core we may be forced to call `sched_yield()` or similar.

Also I suppose that you removed the timeout? Otherwise the test process should be killed with SIGABORT after about 5 minutes.

We could also disable these tests on single core, however I have seen that at least *some* of the races can still happen on single core, at least with full preemption.

**Comment by ycliang-tw** [comment]
Thanks for the timely response!

Yes, I removed it to find out how long it would take for a single core to finish.

At first glance, the test would report FAIL with SIGABRT every time.
Found out that is because the timeout mechanism.
I am just curious and trying to make sense of the situation, so there's no need to disable these tests.

As to calling `sched_yield( )`, what I can immediately think of is 
  1. count the number of loops that the thread is do tst_atomic_load
  2. when a certain number is reached, say INT_MAX
  3. call sched_yield
Do you think this is plausible?

**Comment by richiejp** [comment]
Thanks, interesting suggestion! The problem is though that we only increment this atomic counters once while spin waiting. The `spins` variable is updated every loop, but we only use that in `end_race`. Still it could be used in all cases to periodically call sched_yield, but then we have to pick an appropriate period for the current machine.

I think we should always call `sched_yield` on single core to allow the other thread to progress. The extra branch should not effect multi-core much, but it still needs thorough testing.

**Comment by ycliang-tw** [comment]
Totally Agreed! 

I've tested it (call sched_yield only on single core) on both single core and multi core machine and it works well !
It takes around 5~5 minutes and a half to finish on single core and around 2 minutes on multi core machine that I use,
which does not deviate much from the original execution time for multi core machine. 

Thanks for the suggestion!

I will send a patch later for you to review and I think we can close this issue!
Thanks again!
