### ISSUE TITLE
pselect01 test fails easily

### ISSUE THREAD

**Issue by ycliang-tw** [linux-test-project/ltp#771]
Hi,

I am doing tests on RISC-V platform, and pselect01 testcase fails easily.
If I understand it correctly, pselect01 tries to test the accuracy of pselect's timeout.
I am curious that
1. Does the formula for computing threshold come from heuristic?
    I've found several mails on mailing list regarding the formation of this formula, which seems to be a result of measuring the timeout for different platforms. ( `400 us for context switch, 2 * monotonic_resolution, slack_per_syscall` )
2. What are the possible indications of the failure?
    From what I can tell, this could indicate that the hardware (e.g. real time clock) fails to support this kind of time granularity. Or maybe I misunderstand something?

Thanks in advance,
Leo

**Comment by metan-ucw** [comment]
Sorry for the late response.

There are several tests that asserts kernel timer precision, clock_nanosleep02, epoll_wait02, futext_wait05, nanosleep01, poll02, prctl09, pselect01 and select02. All these tests use common library code that:

* runs particular syscall N times and measure the sleep interval
* if any of the measurements is less that the requested sleep time we fail the test
* if any of the measurements is more than 10 * times what we asked for we fail the test
* after that some outliners are discarded and we compute truncated mean
* the trucated mean is then compared against the sleep interval + treshold

See lib/tst_timer_test.c for deatils.

This usually works fine on bare metal hardware that is otherwise idle.

Also if pselect01 is the only test that fails and the rest of the tests that assert time precision runs fine something is likely wrong in the pselect() syscall implementation.
