### ISSUE TITLE
perf_event_open01.c:158: perf_event_open failed unexpectedly: TEST_ERRNO=EOPNOTSUPP(95): Operation not supported

### ISSUE THREAD

**Issue by olerem** [linux-test-project/ltp#81]
For some reason this test is always failing.

root@mx6q:/opt/ltp# ./testcases/bin/perf_event_open01
perf_event_open01    1  TFAIL  :  perf_event_open01.c:158: perf_event_open failed unexpectedly: TEST_ERRNO=EOPNOTSUPP(95): Operation not supported

At same time perf_event_open02 seems to work properly.
root@mx6q:/opt/ltp# ./testcases/bin/perf_event_open02
perf_event_open02    0  TINFO  :  overall task clock: 254455926
perf_event_open02    0  TINFO  :  hw sum: 1800001050, task clock sum: 1525280694
perf_event_open02    0  TINFO  :  ratio: 5.994282
perf_event_open02    1  TPASS  :  test passed

IMO, if perf_event_open01 filed becouse this operation is not supported, then it should return 32 instead of 1.

**Comment by metan-ucw** [comment]
The reason why ```perf_event_open01``` fails is likely because it tries bunch of different event types, while the ```perf_event_open02``` uses just two of them.

Looking into the ```perf_event_open01``` we already handle ```EINVAL``` (which means that kernel is too old and does not know the requested event type) and return ```TCONF```. We just need to add the ```ENOTSUPP``` as well. And we should really print which event type is not supported in the ```tst_brkm(TFAIL, ...)``` branch as well.

**Comment by olerem** [comment]
Yes, it is old kernel: 3.14
