### ISSUE TITLE
mremap01 is TBROK on ppc64le

### ISSUE THREAD

**Issue by mnowaksuse** [linux-test-project/ltp#90]
```
<<<test_start>>>
tag=mremap01 stime=1472852641
cmdline="mremap01"
contacts=""
analysis=exit
<<<test_output>>>
mremap01    1  TBROK  :  tst_sig.c:233: unexpected signal SIGBUS(7) received (pid = 15068).
mremap01    2  TBROK  :  tst_sig.c:233: Remaining cases broken
<<<execution_status>>>
initiation_status="ok"
duration=0 termination_type=exited termination_id=2 corefile=no
cutime=17 cstime=12
<<<test_end>>>
```

Logs and test setup: https://openqa.suse.de/tests/539272#downloads.

**Comment by metan-ucw** [comment]
```SIGBUS``` usually means that we attempted to access memory outside the mapped file but I don't see anything wrong with the test here. It opens a file ```lseek()```s and ```write()```s it in order to resize it, then ```mmap()```s it, and then ```mremap()```s it so that the mapping is twice it's size and writes to the memory. And then it fills the memory that corresponds to the mapped file which is likely the place where we get the ```SIGBUS```.

The only thing that caught my eye is that the memory is mapped ```PROT_WRITE``` only, but we do not attempt to read from the mapping at all.

Is that problem 100% reproducible? Can you get a ```strace``` of the failure?

**Comment by jstancek** [comment]
What kernel are you using? What filesystem is on TMPDIR?

**Comment by mnowaksuse** [comment]
Log: [runltp.log.txt](https://github.com/linux-test-project/ltp/files/456580/runltp.log.txt)
Kernel is 4.4 (from SLES12SP2 RC2), heavily patched. There's ext4 on the loopback connected to TMPDIR.

**Comment by metan-ucw** [comment]
@mnowaksuse any chance to get the strace from the failing testcase? Otherwise I doubt that we can figure out what is wrong there.

**Comment by mnowaksuse** [comment]
Haven't seen it fail for quite some time.
