### ISSUE TITLE
regtest for ebpf input validation CVE-2022-23222

### ISSUE THREAD

**Issue by msmeissn** [linux-test-project/ltp#945]
via oss-sec

The exploit code can be found at https://github.com/tr3ee/CVE-2022-23222

**Comment by metan-ucw** [comment]
I guess that it makes sense to write the test in a case that the support for userspace eBPF will be enabled back again one day, which may happen one day due to containers.

**Comment by richiejp** [comment]
Well I reproduced  #944 easily. However this one is slightly more complicated and the PoC doesn't quite match the description.

" First, we
   pass 0xffff........ffff to BPF_FUNC_ringbuf_reserve to get a
   NULL pointer r0"

However they appear to pass PAGE_SIZE in the PoC. I guess I'm missing something or else this can just be substituted with the correct value. So it shouldn't be too hard either.

Also it turns out I am wrong about ptr arithmetic. It's being expanded and contracted as more code is allowed then denied again when vulnerabilities are found. There are specific fixes for these issues as well.

**Comment by richiejp** [comment]
Turns out that PAGE_SIZE is too much so it does return 0. Anyway I submitted tests based on both reproducers. Possibly they are just different ways of triggering the same issue.
